In [1]:
import numpy as np

In [15]:
x = np.array([1,2,3,4,6,7])


In [16]:
print(type(x))

<class 'numpy.ndarray'>


In [17]:
print(x.shape)

(6,)


In [18]:
print(x[0],x[1],x[2])

1 2 3


In [19]:
x[1] = 5 

In [20]:
print(x)

[1 5 3 4 6 7]


In [21]:
y = np.array([[1,2,3],[4,5,6]])

In [22]:
print(y.shape)

(2, 3)


In [24]:
print(y[0,0],y[0,1],y[1,1],y[1,2])

1 2 5 6


In [26]:
z = np.zeros((2,2))

In [27]:
print(z)

[[0. 0.]
 [0. 0.]]


In [32]:
k = np.ones((2,3))

In [33]:
print(k)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
p = np.full((2,4),5)

In [35]:
print(p)

[[5 5 5 5]
 [5 5 5 5]]


In [36]:
p[1,2]=9

In [37]:
print(p)

[[5 5 5 5]
 [5 5 9 5]]


In [43]:
e = np.random.random((2,2))
print(e*100)

[[98.58643311 99.23670663]
 [12.76813365 33.39322093]]


In [44]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [61]:
row_r1 = a[2,:]
print(row_r1 , row_r1.shape)

[ 9 10 11 12] (4,)


In [63]:
col_c1 = a[:,1]
print(col_c1 , col_c1.shape)

[ 2  6 10] (3,)


In [64]:
print(a[0,0] , a[1,1], a[2,0])

1 6 9


In [78]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Create a new array from which we will select elements and update them 

In [79]:
r = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
print(r,r.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]] (4, 3)


In [80]:
r[1,1] = 587

In [81]:
print(r)

[[  1   2   3]
 [  4 587   6]
 [  7   8   9]
 [ 11  12  13]]


In [82]:
d = np.array([0,2,0,2])

In [83]:
print(r[np.arange(4),d])

[ 1  6  7 13]


In [84]:
r[np.arange(4),d]+=10
print(r)

[[ 11   2   3]
 [  4 587  16]
 [ 17   8   9]
 [ 11  12  23]]


# Boolean Array indexing : Frequently this type of indexing is used elements of an array that satisfy some condition

In [85]:
bo = np.array([[1,2],[3,4],[5,6]])

In [86]:
bool_idx = (bo>2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [87]:
print(bo[bool_idx])

[3 4 5 6]


In [88]:
# Find Out DataTypes 

In [89]:
bo = np.array([[1,2],[3,4],[5,6]])
print(bo.dtype)

int64


In [91]:
bo = np.array([[1,2.0],[3.0,4],[5,6]])
print(bo.dtype)

float64


# Array Maths

In [93]:
x = np.array([[1,2],[3,4]])
y = np.array([[3,4],[5,6]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [94]:
print(x-y)

[[-2 -2]
 [-2 -2]]


In [96]:
print(np.add(x,y))

[[ 4  6]
 [ 8 10]]


In [99]:
print(np.sum(x))
print(np.sum(y))

10
18


In [100]:
print(np.sqrt(x))
print(np.sqrt(y))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [101]:
print(x/y)

[[0.33333333 0.5       ]
 [0.6        0.66666667]]


In [102]:
print(x*y)

[[ 3  8]
 [15 24]]


In [105]:
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.subtract(x,y))

[[ 3  8]
 [15 24]]
[[0.33333333 0.5       ]
 [0.6        0.66666667]]
[[-2 -2]
 [-2 -2]]


# We use the dot function to compute inner products of vectors


In [107]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10]) 
w = np.array([11,12])

In [111]:
# Inner product of vectors
print(v.dot(w))
print(np.dot(v,w))

219
219


In [112]:
print(x.dot(v))
print(np.dot(x,v))

[29 67]
[29 67]


In [119]:
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


# Transposing a matrix

In [137]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [140]:
print(x.T) # Transposing the array means that , we are changing the row 
           # into the columns and columns into rows
print(y.T)

[[1 3]
 [2 4]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [123]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])

In [124]:
print(v+x)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [126]:
v = np.array([1,2]) 
w = np.array([4,5])

In [127]:
print(v*w)

[ 4 10]


In [141]:
v = np.array([1,2,3]) # v has shape 3 
w = np.array([4,5,6]) # w has shape 2

In [163]:
print(np.reshape(v,(3,1))*w.shape)
print()
print(v*w)

# Tranposing 
vt = v.T
print(vt)

[[3]
 [6]
 [9]]

[ 4 10 18]
[1 2 3]


In [158]:
print(v)
print(np.reshape(v,(3,1))*[2,3])

[1 2 3]
[[2 3]
 [4 6]
 [6 9]]
