In [1]:
import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1. 
Output: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] 

In [119]:
x = np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49.

In [14]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3. Create a 3x3x3 array with random values. 

In [30]:
r = np.random.random((3,3,3))*100
print(r)

[[[85.96996182 72.37937899 34.80634098]
  [81.10434255 81.62486001 54.65709529]
  [70.20179642 46.60180593 80.57635871]]

 [[30.8119682   7.28743803 79.32282398]
  [14.63724146 99.56625765 80.03252046]
  [ 4.55036514 32.0883623  98.36762395]]

 [[46.49535938 35.63792984 56.53552769]
  [33.41759636 36.54934368 14.93594031]
  [88.39163321 45.52202164  0.20149151]]]


# 4. Create a 10x10 array with random values and find the minimum and maximum values. 

In [39]:
new_r = np.random.random((10,10))*100
# print(new_r)
print(new_r.min())
print(new_r.max())

1.4953049491189363
98.90502992712798


# 5. Create a random vector of size 30 and find the mean value.

In [42]:
rv = np.random.random(30)*100
print(rv.mean())

47.42958443727786


# 6. Create a 2d array with 1 on the border and 0 inside. 
Output: <br>
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] <br>
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] <br>
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] <br>
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] <br>
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] <br>
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] <br>
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] <br>
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] <br>
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.] <br>
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

In [53]:
A2d = np.zeros((10,10))
# print(A2d)
A2d[0,:] =1 
A2d[:,0] = 1 
A2d[9,:]=1
A2d[:,9]=1
print(A2d)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 7. Create a 8x8 matrix and fill it with a checkerboard pattern.
Output:  <br>
[[0 1 0 1 0 1 0 1] <br>
[1 0 1 0 1 0 1 0]  <br>
[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]  <br>
[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]  <br>
[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]]  

In [118]:
m8 = np.ones((8,8))
# m8[::2,::2]=0    # fixed the index row of 0,2,4,6  corent one /...... ... 

# m8[::2]=0 # it select the even rows and turn then 0 
# m8[1::2]=0 # it is selecting all the the odd rows and turning them 0 
# m8[1::2,1::2] = 0 # fixed the idx of row 1,3,5,7 corrent one / ..... ./. ./

m8[0::2,0::2] = 0 
m8[1::2,1::2] =0

print(m8)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 8. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal. 
Output: 
[[0 0 0 0 0] 
[1 0 0 0 0] 
[0 2 0 0 0] 
[0 0 3 0 0] 
[0 0 0 4 0]] 

In [65]:
m5 = np.zeros((5,5))

m5[1,0] =1
m5[2,1] =2
m5[3,2] =3
m5[4,3] =4 
print(m5)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 9. Create a random vector of size 10 and sort it.

In [72]:
v10 = np.random.random(10)*100
print(np.sort(v10))


[ 8.230088   36.19754972 41.98491428 57.24710384 57.77395804 58.56969721
 62.98561937 64.75991311 70.74752213 73.81448928]


# 10. Create random vector of size 10 and replace the maximum value by 0.

In [78]:
rv10= np.random.random(10)*100
print(rv10)
rv10[rv10.argmax()] = 0
print(rv10)

[49.83837033 17.14611337 86.65214231 64.90576812 80.927051    4.6570934
 80.35068351 63.04221247 99.5304931  66.75943923]
[49.83837033 17.14611337 86.65214231 64.90576812 80.927051    4.6570934
 80.35068351 63.04221247  0.         66.75943923]
